### ISSUE TITLE
Back button on browser takes me to previous page not to About Us listing

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#35] opened 2015-02-28 18:22 UTC
On About Us page when I hit any of the options in listing

![image](https://cloud.githubusercontent.com/assets/1317442/6427385/fbd75cec-bf97-11e4-8222-fb0787389f4a.png)

I cant come back to this back when I hit the back button on browser it takes me to previous page, not the About Us listing page

So it's better to fix all Back button's including this one, but in this page it should show the listing because it is using Client-side

![image](https://cloud.githubusercontent.com/assets/1317442/6427391/243f250c-bf98-11e4-8020-fec752cb1bb0.png)

Hope it makes sense

**Comment by umayr** [comment] 2015-02-28 19:38
The back button doesn't work at all. It'll be our final thing.

**Comment by umayr** [comment] 2015-03-23 00:41
Duplicate of #8

**Closed as completed by umayr** 2015-03-23 00:41 UTC
Labels: bug, duplicate, internal, P1
