### ISSUE TITLE
The “More Service “ is not navigating from drop down menu and main menu in safari

### ISSUE THREAD

**Issue by zubairahmed-ai** [umayr/boston-kreme#16] opened 2015-01-28 17:41 UTC
The “More Service “ is not navigating from drop down menu and main menu in safari

Steps to Reproduce:
1. Go to Application 
2. Select “More Service “

**Comment by umayr** [comment] 2015-03-23 00:38
Duplicate of #17

**Closed as completed** 2015-03-23 00:38 UTC
Labels: duplicate, external, P2
